framework:
    translator: { fallbacks: ['%locale%'] }
    secret: '%env(APP_SECRET)%'
    default_locale: en
    #csrf_protection: true
    #http_method_override: true
    session:
        handler_id: ~
        cookie_secure: auto
        cookie_samesite: lax

    #esi: true
    #fragments: true
    php_errors:
        log: true
    templating:
        engines: ['twig', 'php']
    ide: 'phpstorm'