#index:
#    path: /
#    controller: App\Controller\DefaultController::index
_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"
fos_user:
  resource: "@FOSUserBundle/Resources/config/routing/all.xml"
notification:
  path: /notification
  controller: null
notifications:
  path: /notifications
  controller: null